Name- Prakhar Bansal

Task 1

Classification Problem

Dataset- Loan approval

In [80]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

file_path='dataset.csv'
df = pd.read_csv(file_path)

In [65]:
df.head()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0        1                  2       Graduate             No        9600000   
1        2                  0   Not Graduate            Yes        4100000   
2        3                  3       Graduate             No        9100000   
3        4                  3       Graduate             No        8200000   
4        5                  5   Not Graduate            Yes        9800000   

    loan_amount   loan_term   cibil_score   residential_assets_value  \
0      29900000          12           778                    2400000   
1      12200000           8           417                    2700000   
2      29700000          20           506                    7100000   
3      30700000           8           467                   18200000   
4      24200000          20           382                   12400000   

    commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                  17600000              22700000            8000000   
1                   2200000               8800000            3300000   
2                   4500000              33300000           12800000   
3                   3300000              23300000            7900000   
4                   8200000              29400000            5000000   

   loan_status  
0     Approved  
1     Rejected  
2     Rejected  
3     Rejected  
4     Rejected

In [66]:
df.describe()
df.dropna()

loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000   
1           2                  0   Not Graduate            Yes        4100000   
2           3                  3       Graduate             No        9100000   
3           4                  3       Graduate             No        8200000   
4           5                  5   Not Graduate            Yes        9800000   
...       ...                ...            ...            ...            ...   
4264     4265                  5       Graduate            Yes        1000000   
4265     4266                  0   Not Graduate            Yes        3300000   
4266     4267                  2   Not Graduate             No        6500000   
4267     4268                  1   Not Graduate             No        4100000   
4268     4269                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000   
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000   
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

      loan_status  
0        Approved  
1        Rejected  
2        Rejected  
3        Rejected  
4        Rejected  
...           ...  
4264     Rejected  
4265     Approved  
4266     Rejected  
4267     Approved  
4268     Approved  

[4269 rows x 13 columns]

We add label encoder to convert object datatype to int64.

In [67]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for col in df.columns:
    if df[col].dtype=='object':
        df[col]=le.fit_transform(df[col])

In [68]:
print(df.shape)
print(df.columns)

(4269, 13)
Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')


We define hyperparameters for the model.

In [69]:
x = df[[' no_of_dependents', ' education', ' self_employed', ' income_annum', ' loan_amount', ' loan_term', ' cibil_score', ' residential_assets_value', ' commercial_assets_value',' luxury_assets_value', ' bank_asset_value']]
y = df[' loan_status']

We import Train-Test Split from sklearn library.


In [70]:
from sklearn.model_selection import train_test_split

In [71]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size = 0.30, random_state = 0)
X_train = X_train.replace([np.inf, -np.inf], np.nan)
X_train = X_train.dropna()

In [72]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'mean')
X_train_imp = imputer.fit_transform(X_train)
X_test_imp = imputer.fit_transform(X_test)
Y_train_imp = imputer.fit_transform(Y_train.values.reshape(-1,1))

In [73]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix

In [74]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(X_train_imp, Y_train_imp)

Y_predict = model.predict(X_test_imp)

accuracy = accuracy_score(Y_predict, Y_test)*100
recall = recall_score(Y_predict, Y_test)*100
f1 = f1_score(Y_predict, Y_test)*100
precision = precision_score(Y_predict, Y_test)*100
matrix = confusion_matrix(Y_predict, Y_test)
print("accuracy",accuracy, '%')
print("recall",recall, '%')
print("precision",precision, '%')
print("f1",f1, '%')
print("confusion matrix",matrix,sep="\n")



accuracy 55.5815768930523 %
recall 41.07648725212464 %
precision 28.65612648221344 %
f1 33.76018626309663 %
confusion matrix
[[567 361]
 [208 145]]


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [75]:
model = KNeighborsClassifier(n_neighbors = 10,weights = 'uniform')
model.fit(X_train_imputed, Y_train_imputed)

Y_predict = model.predict(X_test_imp)

accuracy = accuracy_score(Y_predict, Y_test)*100
recall = recall_score(Y_predict, Y_test)*100
f1 = f1_score(Y_predict, Y_test)*100
precision = precision_score(Y_predict, Y_test)*100
matrix = confusion_matrix(Y_predict, Y_test)
print("accuracy",accuracy, '%')
print("recall",recall, '%')
print("precision",precision, '%')
print("f1",f1, '%')
print("confusion matrix",matrix,sep="\n")

accuracy 65.26151444184231 %
recall 65.64102564102564 %
precision 25.296442687747035 %
f1 36.51925820256776 %
confusion matrix
[[708 378]
 [ 67 128]]


In [76]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
model = RandomForestClassifier()
model.fit(X_train_imputed, Y_train_imputed)

Y_predict = model.predict(X_test_imp)

accuracy = accuracy_score(Y_predict, Y_test)*100
recall = recall_score(Y_predict, Y_test)*100
f1 = f1_score(Y_predict, Y_test)*100
precision = precision_score(Y_predict, Y_test)*100
matrix = confusion_matrix(Y_predict, Y_test)
print("accuracy",accuracy, '%')
print("recall",recall, '%')
print("precision",precision, '%')
print("f1",f1, '%')
print("confusion matrix",matrix,sep="\n")

accuracy 99.76580796252928 %
recall 99.60552268244575 %
precision 99.80237154150198 %
f1 99.70384995064165 %
confusion matrix
[[773   1]
 [  2 505]]


In [78]:
from sklearn.ensemble import GradientBoostingClassifier

In [79]:
model = GradientBoostingClassifier()
model.fit(X_train_imputed, Y_train_imputed)

Y_predict = model.predict(X_test_imp)

accuracy = accuracy_score(Y_predict, Y_test)*100
recall = recall_score(Y_predict, Y_test)*100
f1 = f1_score(Y_predict, Y_test)*100
precision = precision_score(Y_predict, Y_test)*100
matrix = confusion_matrix(Y_predict, Y_test)
print("accuracy",accuracy, '%')
print("recall",recall, '%')
print("precision",precision, '%')
print("f1",f1, '%')
print("confusion matrix",matrix,sep="\n")

accuracy 98.98516783762685 %
recall 99.59758551307847 %
precision 97.82608695652173 %
f1 98.703888334995 %
confusion matrix
[[773  11]
 [  2 495]]
